[workspace]
members = [
    "contracts/vesting_contracts",
    "contracts/grant_contracts",
]
resolver = "2"

[workspace.dependencies]
soroban-sdk = { version = "25.1.1" }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
